name: Application CI
on: [push, pull_request]
jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  pipeline:
    name: snyk gradle plugin pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install Snyk CLI from NPM
        run: npm install -g snyk
      - name: Clean build
        run: |
          chmod +x gradlew
          ./gradlew clean build -x functionalTest
      - name: Functional test
        run: ./gradlew functionalTest
      - name: Snyk Test
        run: snyk test
      - name: Snyk Monitor
        run: snyk monitor